# Generated by Django 3.1.5 on 2021-01-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='alt_first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt first name'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='alt_last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt last name'),
        ),
    ]
