# Generated by Django 3.1.5 on 2021-01-28 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notice', '0001_initial'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='match id')),
                ('match_type', models.CharField(choices=[('Strong Match', 'Strong Match'), ('Possible Match', 'Possible Match'), ('Weak Match', 'Weak Match')], max_length=25)),
                ('notice', models.ForeignKey(db_column='notice_id', on_delete=django.db.models.deletion.CASCADE, to='notice.notice', verbose_name='notice')),
                ('record', models.ForeignKey(db_column='record_id', on_delete=django.db.models.deletion.CASCADE, to='record.record', verbose_name='record')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'db_table': 'tblmatch',
            },
        ),
    ]
